### ISSUE TITLE
Legend for the color and slow down the movement of the node

### ISSUE THREAD

**Issue by chaupmcs** [imohitmayank/jaal#11]
Hi,

Thank you for this cool visualization.
I am trying to use this for my network. It works really well.
I have some suggestions as follows.
1. When coloring the nodes/edges, it's hard to tell which color is what. So, it would be great to see the legend
2. In my network, some nodes have quite many neighbors which make the sub-graph moving quite fast. It may be better to keep the network more still.

Thank you!

**Comment by imohitmayank** [comment]
Hi @chaupmcs, glad you liked Jaal! 
So yes, agree with the 1st point -- created #12  for this. 
Regarding the 2nd point, plz help me with some questions -- does this movement stops after some time? Or it keeps going on? Also, does this happens partially for a section of the graph (with the rest part constant) or it happens for the complete graph? 
Thnx!

**Comment by chaupmcs** [comment]
Hi @imohitmayank,

Thank you for the reply.

Regarding the second point:
- The movement doesn't stop
- It only happens on the dense sub-graph where many nodes connecting to each other. It's a bit hard to click or focus on the name of the nodes.

For the purpose of reproducibility, I attach [the data here](https://drive.google.com/drive/folders/17KOyWOkr3O2nNLUWfG082lBDtS6w9ptl?usp=sharing).


An overview of my network

![gif2](https://user-images.githubusercontent.com/42042991/110369366-ed5b9900-800f-11eb-938d-d24606ba7ac2.gif)

**Comment by imohitmayank** [comment]
@chaupmcs  update -- the latest version of Jaal (v0.0.7) now supports the Legends feature for color setting. The preview is as such, 
![jaal_search](https://user-images.githubusercontent.com/1883779/111029629-b7f5e780-8423-11eb-9628-69c5e20c2571.gif)

**Comment by imohitmayank** [comment]
Also, thank you for sharing the data and raising the slowness as an issue. I am looking into it, but most probably that is due to the physics engine which tries to stabilize the network after some iterations. 
As the number of nodes and edges increases, it becomes quite difficult to stabilize the network quickly. Nevertheless, playing with the data and looking for a workaround. For the time being, you can try to filter the data (by the filter setting) so that the network size is quite manageable. Thnx again!

**Comment by chaupmcs** [comment]
Hi @imohitmayank,

Thank you for your help!
