### ISSUE TITLE
Filter by "from" it doesn't work

### ISSUE THREAD

**Issue by carlosmacapuna** [imohitmayank/jaal#39]
All other columns of the filter on edges work, except from:

from == "Jon-Snow"

**Comment by imohitmayank** [comment]
Hey @carlosmacapuna, the issue as suggested in the [DataFrame.Query](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html) doc, is due to `from` being a python keyword. To handle such scenarios, the doc suggests enclosing the column name under backticks. Doing same, you can perform the search. For example, \`from\`=='Jon-Snow' should work, as shown in the image. 
![image](https://user-images.githubusercontent.com/1883779/135712167-9f3c71ff-70f1-4a25-9dc2-c6636582bb1a.png)

**Comment by carlosmacapuna** [comment]
Wonder! Thank you very much!
